# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Post.destroy_all
User.destroy_all

User.create!({first_name: 'Guest', last_name: 'User', email: 'guestuser@gmail.com', password: 'NobodyWillGuessThisPassword17'})
User.create!({first_name: 'Larry', last_name: 'Johnson', email: 'larryjohnson@gmail.com', password: 'NobodyWillGuessThisPassword17'})
User.create!({first_name: 'Taylor', last_name: 'Williams', email: 'taylorwilliams@gmail.com', password: 'NobodyWillGuessThisPassword17'})
User.create!({first_name: 'Ronnie', last_name: 'Brown', email: 'ronniebrown@gmail.com', password: 'NobodyWillGuessThisPassword17'})
User.create!({first_name: 'Stacy', last_name: 'Jones', email: 'stacyjones@gmail.com', password: 'NobodyWillGuessThisPassword17'})
User.create!({first_name: 'Erin', last_name: 'Garcia', email: 'eringarcia@gmail.com', password: 'NobodyWillGuessThisPassword17'})
User.create!({first_name: 'Paula', last_name: 'Miller', email: 'paulamiller@gmail.com', password: 'NobodyWillGuessThisPassword17'})
User.create!({first_name: 'Jennifer', last_name: 'Davis', email: 'jenniferdavis@gmail.com', password: 'NobodyWillGuessThisPassword17'})
User.create!({first_name: 'Eunice', last_name: 'Rodriguez', email: 'eunicerodriguez@gmail.com', password: 'NobodyWillGuessThisPassword17'})
User.create!({first_name: 'Dennis', last_name: 'Anderson', email: 'dennisanderson@gmail.com', password: 'NobodyWillGuessThisPassword17'})
User.create!({first_name: 'Terrance', last_name: 'Hernandez', email: 'terrancehernadez@gmail.com', password: 'NobodyWillGuessThisPassword17'})
User.create!({first_name: 'Gary', last_name: 'Thomas', email: 'garythomas@gmail.com', password: 'NobodyWillGuessThisPassword17'})
User.create!({first_name: 'Wayne', last_name: 'Moore', email: 'waynemoore@gmail.com', password: 'NobodyWillGuessThisPassword17'})
User.create!({first_name: 'Emmons', last_name: 'Clark', email: 'emmonsclark@gmail.com', password: 'NobodyWillGuessThisPassword17'})
User.create!({first_name: 'Fozia', last_name: 'Sanchez', email: 'foziasanchez@gmail.com', password: 'NobodyWillGuessThisPassword17'})
User.create!({first_name: 'Sophia', last_name: 'Ramirez', email: 'sophiaramirez@gmail.com', password: 'NobodyWillGuessThisPassword17'})
User.create!({first_name: 'Arthelle', last_name: 'Lewis', email: 'arthellelewis@gmail.com', password: 'NobodyWillGuessThisPassword17'})
User.create!({first_name: 'Teresa', last_name: 'Robinson', email: 'teresarobinson@gmail.com', password: 'NobodyWillGuessThisPassword17'})
User.create!({first_name: 'Rachel', last_name: 'Walker', email: 'rachelwalker@gmail.com', password: 'NobodyWillGuessThisPassword17'})
User.create!({first_name: 'Delaney', last_name: 'Young', email: 'delaneyyoung@gmail.com', password: 'NobodyWillGuessThisPassword17'})
User.create!({first_name: 'Claudia', last_name: 'Torres', email: 'claudiatorres@gmail.com', password: 'NobodyWillGuessThisPassword17'})
User.create!({first_name: 'Rocco', last_name: 'Nguyen', email: 'rocconguyen@gmail.com', password: 'NobodyWillGuessThisPassword17'})
User.create!({first_name: 'Daphne', last_name: 'Baker', email: 'daphnebaker@gmail.com', password: 'NobodyWillGuessThisPassword17'})
User.create!({first_name: 'Max', last_name: 'Nelson', email: 'maxnelson@gmail.com', password: 'NobodyWillGuessThisPassword17'})
User.create!({first_name: 'Ricky', last_name: 'Hall', email: 'rickyhall@gmail.com', password: 'NobodyWillGuessThisPassword17'})
User.create!({first_name: 'Gabby', last_name: 'Campbell', email: 'gabbycampbell@user.com', password: 'NobodyWillGuessThisPassword17'})
User.create!({first_name: 'Charles', last_name: 'Richardson', email: 'charlesrichardson@user.com', password: 'NobodyWillGuessThisPassword17'})
User.create!({first_name: 'Jasmine', last_name: 'Roberts', email: 'jasmineroberts@user.com', password: 'NobodyWillGuessThisPassword17'})
User.create!({first_name: 'Sean', last_name: 'Mitchell', email: 'seanmitchell@user.com', password: 'NobodyWillGuessThisPassword17'})
User.create!({first_name: 'Carter', last_name: 'Roberts', email: 'carterroberts@user.com', password: 'NobodyWillGuessThisPassword17'})
User.create!({first_name: 'Whitney', last_name: 'Thompson', email: 'whitneythompson@user.com', password: 'NobodyWillGuessThisPassword17'})

User.all.each do |user|
  user.profile_picture.attach(io: File.open("/Users/efrem/Desktop/FaceCrook/app/assets/images/default-male-pic.jpeg"), filename: "Default")
end

Post.create!({author_id: 1, body: "Why did the football coach go to the bank? To get his quarter back."})
Post.create!({author_id: 2, body: "Why can't a leopard hide? She's always spotted."})
Post.create!({author_id: 3, body: "Air used to be free at the gas station, now it costs 2.50. You want to know why? Inflation."})
Post.create!({author_id: 4, body: "Why did the orange lose the race? It ran out of juice."})
Post.create!({author_id: 5, body: "I told my wife that a husband is like a fine wine: we just get better with age. The next day she locked me in the cellar."})
Post.create!({author_id: 6, body: "Why does a husband lead a dog's life? He comes in with muddy feet, gets comfortable by the fire, and waits to be fed."})
Post.create!({author_id: 7, body: "Did you hear about the claustrophobic astronaut? He just wanted a bit more space."})
Post.create!({author_id: 8, body: "How many telemarketers does it take to change a light bulb? Only one, but he has to do it during dinner."})
Post.create!({author_id: 9, body: "How you fix a broken pumpkin? With a pumpkin patch."})
Post.create!({author_id: 10, body: "Why are fish so smart? They live in schools!"})
Post.create!({author_id: 11, body: "What's the best thing about Switzerland? I don't know, but the flag is a big plus."})
Post.create!({author_id: 12, body: "Why did the man fall down the well? Because he couldn’t see that well!"})
Post.create!({author_id: 13, body: "Why do peppers make such good archers? Because they habanero."})
Post.create!({author_id: 14, body: "What did the sink tell the toilet? You look flushed!"})
Post.create!({author_id: 15, body: "Where do boats go when they're sick? To the dock."})
Post.create!({author_id: 16, body: "What has ears but cannot hear? A cornfield!"})
Post.create!({author_id: 17, body: "Stop looking for the perfect match; use a lighter."})
Post.create!({author_id: 18, body: "I'm so good at sleeping that I do it with my eyes closed."})
Post.create!({author_id: 19, body: "I hated facial hair but then it grew on me."})
Post.create!({author_id: 20, body: "I was going to tell a time-traveling joke, but you didn't like it."})
Post.create!({author_id: 21, body: "I was going to tell a time-traveling joke, but you didn't like it."})
Post.create!({author_id: 22, body: "I ordered a chicken and an egg online. I'll let you know."})
Post.create!({author_id: 23, body: "I'm reading an anti-gravity book. I can't put it down!"})
Post.create!({author_id: 24, body: "What state is known for its small drinks? Minnesota."})
Post.create!({author_id: 25, body: "What's Forrest Gump's password? 1forrest1"})
Post.create!({author_id: 26, body: "What do houses wear? An address."})
Post.create!({author_id: 27, body: "What did the two pieces of bread say on their wedding day? It was loaf at first sight."})
Post.create!({author_id: 28, body: "What kind of shoes does a lazy person wear? Loafers."})
Post.create!({author_id: 29, body: "What did the ocean say to the beach? Nothing, it just waved."})
Post.create!({author_id: 30, body: "What happens when a snowman throws a tantrum? He has a meltdown."})

Post.create!({author_id: 1, body: "Three presidents, all Founding Fathers—John Adams, Thomas Jefferson, and James Monroe—died on July 4. Presidents Adams and Jefferson also died the same year, 1826; President Monroe died in 1831. Coincidence? You decide"})
Post.create!({author_id: 2, body: "The Barbie doll’s full name is Barbara Millicent Roberts, from Willows, Wisconsin. Her birthday is March 9, 1959, when she was first displayed at the New York Toy Fair."})
Post.create!({author_id: 3, body: "There actually aren’t “57 varieties” of Heinz ketchup, and never were. Company founder H.J. Heinz thought his product should have a number, and he liked 57. Hint: Hit the glass bottle on the “57,” not the bottom, to get the ketchup to flow."})
Post.create!({author_id: 4, body: "The tallest man ever recorded was American giant Robert Wadlow (1918–1940), who stood 8 feet 11 inches. Wadlow’s size was the result of abnormally enlarged pituitary gland."})
Post.create!({author_id: 5, body: "The tallest living man is 37-year-old Sultan Kosen, from Turkey, who is 8 feet, 2.8 inches, who set the record in 2009. His growth is also due to a pituitary issue."})
Post.create!({author_id: 6, body: "The oldest person ever to have lived (whose age could be authenticated), a French woman named Jeanne Louise Calment, was 122 years old when she died in 1997."})
Post.create!({author_id: 7, body: "Sliced bread was first manufactured by machine and sold in the 1920s by the Chillicothe Baking Company in Missouri. It was the greatest thing since…unsliced bread?"})
Post.create!({author_id: 8, body: "The Earl of Sandwich, John Montagu, who lived in the 1700s, reportedly invented the sandwich so he wouldn’t have to leave his gambling table to eat."})
Post.create!({author_id: 9, body: "The first college football game was played on November 6, 1869, between Rutgers and Princeton (then known as the College of New Jersey) in New Brunswick, New Jersey. Rutgers won."})
Post.create!({author_id: 10, body: "Experiments in universities have actually been carried out to figure out how many licks it takes to get to the center of a Tootsie Pop, both with machine and human lickers (because this is important scientific knowledge!). The results ranged from 252 to 411."})
Post.create!({author_id: 11, body: "The Four Corners is the only spot in the US where you can stand in four states at once: Utah, Colorado, Arizona and New Mexico. "})
Post.create!({author_id: 12, body: "Canada is south of Detroit (just look at a map)."})
Post.create!({author_id: 13, body: "The original name for the search engine Google was Backrub. It was renamed Google after the googol, which is the number one followed by 100 zeros."})
Post.create!({author_id: 14, body: "The oldest-known living land animal is a tortoise named Jonathan, who is 187 years old. He was born in 1832 and has lived on the island of St. Helena in the Atlantic Ocean since 1882."})
Post.create!({author_id: 15, body: "Bats are the only mammal that can actually fly."})
Post.create!({author_id: 16, body: "Wombats are the only animal whose poop is cube-shaped. This is due to how its intestines form the feces. The animals then stack the cubes to mark their territory."})
Post.create!({author_id: 17, body: "The most common wild bird in the world isn’t the sparrow or blue jay—it’s the red-billed quelea, which live in Africa and have an estimated population of 1.5 billion."})
Post.create!({author_id: 18, body: "The heart of the blue whale, the largest animal on earth, is five feet long and weighs 400 pounds. The whale in total weighs 40,000 pounds."})
Post.create!({author_id: 19, body: "For comparison, an elephant’s heart weighs around 30 pounds. And a human heart? A mere 10 ounces."})
Post.create!({author_id: 20, body: "Elephants can’t jump."})
Post.create!({author_id: 21, body: "Octopuses have three hearts."})
Post.create!({author_id: 22, body: "Cows don’t actually have four stomachs; they have one stomach with four compartments."})
Post.create!({author_id: 23, body: "The platypus doesn’t have a stomach at all: Their esophagus goes straight to their intestines."})
Post.create!({author_id: 24, body: "This is one animal myth that’s true: Eating parts of a pufferfish can kill you because, in a defense mechanism to ward off predators, it contains a deadly chemical called tetrodotoxin. There’s enough in one pufferfish to kill 30 people—and there’s no antidote. Still, pufferfish, called fugu, is a highly-prized delicacy in Japan, but can only be prepared by well-trained chefs."})
Post.create!({author_id: 25, body: "Polar bears have black skin. And actually, their fur isn’t white—it’s see-through, so it appears white as it reflects light."})
Post.create!({author_id: 26, body: "Tigers’ skin is actually striped, just like their fur. Also, no two fur patterns are alike."})
Post.create!({author_id: 27, body: "Flamingoes are only pink because of chemicals called carotenoids in the algae and fish (which also eat the algae) they eat; their feathers are grayish white when they’re born."})
Post.create!({author_id: 28, body: "Mosquitoes are the deadliest animal in the world: They kill more people than any other creature, due to the diseases they carry."})
Post.create!({author_id: 29, body: "With 3.572 billion viewers, half the world’s population watched the 2018 FIFA World Cup of soccer (or football, as many international fans call it), which is held every four years. That number is on par with the 2016 Summer Olympics; but only a quarter of the world watched the less-popular Winter Olympics in 2018."})
Post.create!({author_id: 30, body: "There are no muscles in your fingers: Their function is controlled by muscles in your palms and arms."})

Post.create!({author_id: 1, body: "The asteroid that ended the dinosaurs was technically the highest ratio of killing birds to one stone in Earth's history."})
Post.create!({author_id: 2, body: "A different version of you exists in the minds of everyone who knows you."})
Post.create!({author_id: 3, body: "As an identical triplet, you are simultaneously one of the rarest and most common people on the planet."})
Post.create!({author_id: 4, body: "Making a typo in an online argument is the equivalent of [your] voice cracking in a verbal argument."})
Post.create!({author_id: 5, body: "Once we have self-driving cars, wipers will no longer be essential, because the car doesn't need a clean windshield to drive. Only humans do."})
Post.create!({author_id: 6, body: "Kids will never understand the poignant self-satisfaction of slamming a phone down on the cradle to hang up on someone and end an angry conversation."})
Post.create!({author_id: 7, body: "There could be a viral video of you doing something random with millions of views, and you have no idea because you haven't seen it."})
Post.create!({author_id: 8, body: "Gen Z might have been the last generation to know what it’s like to get up early in the morning to catch your favorite cartoons on TV."})
Post.create!({author_id: 9, body: "Someone out there vividly remembers something you said, which you have completely forgotten."})
Post.create!({author_id: 10, body: "When you walk into a 7-Eleven you wouldn’t think it’s an $18 billion company."})
Post.create!({author_id: 11, body: "When we switch to electric vehicles, everything is going to become quieter."})
Post.create!({author_id: 12, body: "Adult life is hard, but at least we don't have to do P.E. anymore."})
Post.create!({author_id: 13, body: "It won't be long before people use 'the '20s, the '30s, and the '40s' to describe the 2020s, the 2030s, and the 2040s."})
Post.create!({author_id: 14, body: "If 24-hour clocks started at 23:59 and counted down till 00:01, people might try getting more done."})
Post.create!({author_id: 15, body: "We advocate not judging a book by its cover, but also glorify 'love at first sight."})
Post.create!({author_id: 16, body: "At some point in life, there was a stranger who got disappointed by how your voice sounded when you started talking."})
Post.create!({author_id: 17, body: "Chances are high you are not anyone's best friend."})
Post.create!({author_id: 18, body: "Biscuits and gravy are weird because it’s like, 'Here’s some really wet flour poured over some really dry flour."})
Post.create!({author_id: 19, body: "All adults were children, but not all children will become adults."})
Post.create!({author_id: 20, body: "It’s likely that over 99% of trees that you look at will be still here when you’re dead."})
Post.create!({author_id: 21, body: "The most attractive people you will ever see are often random passersby in public — who you will never see again, not celebrities you can follow on social media."})
Post.create!({author_id: 22, body: "The posted speed limit is the legally accepted maximum limit, but the socially accepted minimum limit."})
Post.create!({author_id: 23, body: "Most people aren't scared of being alone in the dark — they're scared of not being alone in the dark."})
Post.create!({author_id: 24, body: "One day your parents put you down and never picked you up again."})
Post.create!({author_id: 25, body: "An everything bagel is proof that you can seemingly have it all and still have a hole inside you."})
Post.create!({author_id: 26, body: "We go to work by cars each day, taking the same route, but almost never encounter the same cars along the way."})
Post.create!({author_id: 27, body: "If heaven exists, it’s probably going back and doing your life over, but fixing all your mistakes."})
Post.create!({author_id: 28, body: "The 10 years between 25 and 35 are far shorter than the four years between 14 and 18."})
Post.create!({author_id: 29, body: "The fact that bodies decompose and rot after they die just shows how much our bodies do to keep us alive from contaminates."})
Post.create!({author_id: 30, body: "Painkillers are the 'Mute Notifications' option for the body."})

Post.create!({author_id: 1, body: "Humans are afraid of being bitten by spiders even though they have more teeth. Spiders are afraid of being stepped on by humans even though they have more legs."})
Post.create!({author_id: 2, body: "Hearing 'I love you' hits different than 'I love you too."})
Post.create!({author_id: 3, body: "We really don't appreciate the fact that email is free."})
Post.create!({author_id: 4, body: "There are sidewalks in the Cars movies, but they are all cars."})
Post.create!({author_id: 5, body: "4 a.m. is the hour where you’re either up really late or really early."})
Post.create!({author_id: 6, body: "Elementary schoolers who have no control over their transportation are punished more for being late than college students who own cars."})
Post.create!({author_id: 7, body: "Pressing the ‘lock’ button on your car key fob multiple times is the grown-up version of saving your game twice."})
Post.create!({author_id: 8, body: "Being 'on your phone all day' went from sounding very sociable to very unsociable within the span of a decade."})
Post.create!({author_id: 9, body: "Finding an eggshell in an Egg McMuffin is both annoying and reassuring."})
Post.create!({author_id: 10, body: "If you're still pretty young, chances are you still haven't met the majority of people who will attend your funeral."})
Post.create!({author_id: 11, body: "Death is a paradox. It makes everything meaningless while it also gives meaning to everything."})
Post.create!({author_id: 12, body: "The richest person on Earth is technically also the richest person in the universe, since our definition of rich is owning a lot of Earth money, and there's no way for extraterrestrial life to obtain it."})
Post.create!({author_id: 13, body: "Jello isn’t technically boneless."})
Post.create!({author_id: 14, body: "Most people would find licking the inside of a pipe disgusting but wouldn't think twice about drinking water coming from that same pipe."})
Post.create!({author_id: 15, body: "Whenever you eat canned pieces of fruit, you are more than likely sharing one whole fruit with someone hundreds of miles away."})
Post.create!({author_id: 16, body: "Headaches make you realize how much you take not having one for granted."})
Post.create!({author_id: 17, body: "Extra fries in your bag is going to become a thing of the past once fast-food workers are 100% replaced by robots."})
Post.create!({author_id: 18, body: "Maybe midlife crises aren't really crises at all; the person has just reached a point in their life when they can do what they want and don't care what anyone else thinks. The people who are upset by it are just mad that their opinion doesn't matter."})
Post.create!({author_id: 19, body: "In the Cars universe, a movie about humans would probably be a horror movie. Slender creatures made out of flesh and bone riding the lifeless carcasses of cars for their convenience."})
Post.create!({author_id: 20, body: "You probably know more Latin, a dead language, than you do Mandarin, the most common native tongue."})
Post.create!({author_id: 21, body: "You never really know how much fun you're having until you look back at that same moment years later."})
Post.create!({author_id: 22, body: "If Apple had kept its 1976 logo, it wouldn't have to change its logo during pride month."})
Post.create!({author_id: 23, body: "Academic grades are strange in that while you’re in school they are the most heavily weighted indicator of your potential, but they are never considered important after your first job post-school."})
Post.create!({author_id: 24, body: "Your belly button is just your old mouth."})
Post.create!({author_id: 25, body: "A successful marriage ends with watching the other person die."})
Post.create!({author_id: 26, body: "The brain not only named itself, but it also recognized that it named itself and was surprised when it realized that."})
Post.create!({author_id: 27, body: "Koala fingerprints are so close to humans' that they could taint crime scenes."})
Post.create!({author_id: 28, body: "Parrots will selflessly help each other out."})
Post.create!({author_id: 29, body: "Prairie dogs kiss."})
Post.create!({author_id: 30, body: "Ghost crabs growl using teeth in their stomachs."})

Post.create!({author_id: 1, body: "The mantis shrimp has the world's fastest punch."})
Post.create!({author_id: 2, body: "Female lions do 90 percent of the hunting."})
Post.create!({author_id: 3, body: "Temperatures on Venus reach 880 degrees Fahrenheit"})
Post.create!({author_id: 4, body: "Narwhal tusks are really an 'inside out' tooth."})
Post.create!({author_id: 5, body: "And the oldest evidence of domesticated cats dates back 9,500 years."})
Post.create!({author_id: 6, body: "Puffins use twigs to scratch their bodies."})
Post.create!({author_id: 7, body: "Bottlenose dolphins are even more right-handed than humans."})
Post.create!({author_id: 8, body: "There's a kind of ant that only lives in a small area of Manhattan."})
Post.create!({author_id: 9, body: "Cows painted with zebra-like stripes can avoid being bitten by flies."})
Post.create!({author_id: 10, body: "Capuchin monkeys wash their hands and feet in urine."})
Post.create!({author_id: 11, body: "Sperm whales in the Caribbean have an accent."})
Post.create!({author_id: 12, body: "Some pigs in China are the size of bears."})
Post.create!({author_id: 13, body: "Some sharks glow in the dark."})
Post.create!({author_id: 14, body: "Some snails have hairy shells."})
Post.create!({author_id: 15, body: "Cowbirds use secret passwords to teach their young."})
Post.create!({author_id: 16, body: "Baby Tasmanian devils make life-long friendships."})
Post.create!({author_id: 17, body: "A grizzly bear's bite is strong enough to crush a bowling ball."})
Post.create!({author_id: 18, body: "Humpback whales use bubbles to hunt."})
Post.create!({author_id: 19, body: "A housefly buzzes in an F key."})
Post.create!({author_id: 20, body: "Moray eels have a second pair of 'Alien-style' jaws"})
Post.create!({author_id: 21, body: "Ducks can surf."})
Post.create!({author_id: 22, body: "Slow lorises are the only venomous primates."})
Post.create!({author_id: 23, body: "Pigeons can do math."})
Post.create!({author_id: 24, body: "Zebra stripes act as a natural bug repellant."})
Post.create!({author_id: 25, body: "Wild chimps like to drink."})
Post.create!({author_id: 26, body: "Sea otters are adept at using tools."})
Post.create!({author_id: 27, body: "Frogs can freeze without dying."})
Post.create!({author_id: 28, body: "Male horses have way more teeth than their female counterparts."})
Post.create!({author_id: 29, body: "Koalas sleep up to 22 hours a day."})
Post.create!({author_id: 30, body: "A group of ferrets is called a business."})

Post.create!({author_id: 1, body: "Our solar system is about 4.5 billion years old."})
Post.create!({author_id: 2, body: "The largest asteroid in our solar system — Ceres — has a diameter of 580 miles"})
Post.create!({author_id: 3, body: "The North Star changes every 26,000 years."})
Post.create!({author_id: 4, body: "We have mapped nearly 100% of Mars’s surface."})
Post.create!({author_id: 5, body: "The Moon is drifting away from Earth at a rate of 1.5 inches (3.8 cm) a year."})
Post.create!({author_id: 6, body: "Mercury orbits the Sun at an average speed of 107,000 miles per hour (172,000 km/h)."})
Post.create!({author_id: 7, body: "Temperatures on Venus reach 880 degrees Fahrenheit (471 °C)."})
Post.create!({author_id: 8, body: "One light-year is about 6 trillion miles (9 trillion km)."})
Post.create!({author_id: 9, body: "A person who weighs 220 pounds (100 kg) on Earth would weigh only 84 pounds (34 kg) on Mars."})
Post.create!({author_id: 10, body: "Only 5% of the universe is actually visible."})
Post.create!({author_id: 11, body: "Outer space is only 62 miles away."})
Post.create!({author_id: 12, body: "There are three types of galaxies: spiral, elliptical, and irregular."})
Post.create!({author_id: 13, body: "Halley’s comet makes an appearance every 75–76 years."})
Post.create!({author_id: 14, body: "The entire asteroid belt’s total mass is just 3% of the Moon’s mass."})
Post.create!({author_id: 15, body: "You can see eight different galaxies using nothing but the naked eye."})
Post.create!({author_id: 16, body: "Astronomers have made more than 1.4 million observations using the Hubble Space Telescope."})
Post.create!({author_id: 17, body: "Voyager 1 is located around 14.1 billion miles (22.8 billion km) from the Sun."})
Post.create!({author_id: 18, body: "The Milky Way contains around 100 million stars."})
Post.create!({author_id: 19, body: "Neutron stars are about 1.4 times the mass of the Sun."})
Post.create!({author_id: 20, body: "Sun makes up 99% of our entire solar system’s mass."})
Post.create!({author_id: 21, body: "It takes Sun 25 to 35 days to make one full rotation."})
Post.create!({author_id: 22, body: "The Sun produces about 384.6 septillion watts of energy — equivalent of 1,820,000,000 Tsar Bombs."})
Post.create!({author_id: 23, body: "Neutron stars rotate at a speed of 600 times per second."})
Post.create!({author_id: 24, body: "Venus has around 1,600 volcanoes."})
Post.create!({author_id: 25, body: "The Whirlpool Galaxy is around 76,000 light-years in diameter.."})
Post.create!({author_id: 26, body: "On Mars, the temperature at your feet can be 75 degrees Fahrenheit (24 °C), while the temperature around your head is 32 degrees Fahrenheit (0 °C)."})
Post.create!({author_id: 27, body: "Scientists discovered a hydrogen signal from a galaxy located five billion light-years away."})
Post.create!({author_id: 28, body: "The first-ever photographed black hole is three million times the size of Earth."})
Post.create!({author_id: 29, body: "One day on Venus takes 225 Earth days."})
Post.create!({author_id: 30, body: "Jupiter’s Great Red Spot is 10,160 miles (16,350 km) in diameter."})